### ISSUE TITLE
integrate with data formatting/validation library

### ISSUE THREAD

**Issue by smhg** [ccharz/laravel-epc-qr#2]
@ccharz I was pointed to your project as I was maintaining a similar project.
However, it was using a previous version of `endroid/qr-code` and their recent refactoring lead me to a different approach and decouple from them.

The result is [smhg/sepa-qr-data](https://github.com/smhg/sepa-qr-data-php) which turns payment data (iban, name, amount,...) into the EPC format which can then be passed to a QR renderer (endroid/qr-code or similar). This, by design, is a very limited scope.

Would you want to consider incorporating this into your project? This would deduplicate our efforts for validation and formatting. I'd be happy to include any contributions that you'd need to make this work. Including API changes.

**Comment by ccharz** [comment]
I started this project because i maintain multiple laravel projects which use EPC QR Codes and at that time no existing package fit into my dependency structure. So i extracted my code into this package to share it, in case anyone else had the same problem.

By incorporating your QR Data Logic into my project, i would basically make this package completely obsolete because the additional benefit of this package would be less to nothing. I can see that your package is the better - more general way - and if it would have existed a year ago you would have saved me a lot of work ;) 

If thats fine for you, i will incorporate a link to your project, but i don't think integrating your library into this project makes any  sense, because then everybody is better off with your package alone to have less dependencies.

**Comment by smhg** [comment]
I don't think you should look at it that way.
In many occasions I don't think anyone should use sepa-qr-data directly. It is very good to use a package (yours) which incorporates a QR renderer. At the very least for these reasons:
1. So people don't have to choose/don't have to know about a QR rendering library.
2. So you can set the required defaults:
    - error correction needs to be "medium" on endroid/qr-code
    - the character set in the EPC data should match the encoding set on endroid/qr-code
3. To integrate with Laravel.

And at the same time we'd be bundling our efforts on the formatting/validation part. It would be really good to add anything that you need/that's missing to sepa-qr-data.

But, of course, also feel free to close this issue.
